---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  html_notebook: default
  word_document: default
---







## Генерация случайных чисел и распределения

* pois -- Пуассона
* norm -- Гауса
* unif -- равномерное
* exp
* binom

*  p -- функ распред
*  d -- плотность
*  q -- квантили
*  r -- вектор случ чисел




```{r punif}
punif(1.7,1,2)
```

```{r quif}
qunif(0.7,1,2)
```



```{r qnorm}

m_height <- 168
std_height <-12
(crit_height <- qnorm(p = 0.80 ,  mean = m_height,sd = std_height ) )

```




```{r radom norm}
(r_heights <-  rnorm(1000,  mean = m_height,sd = std_height ))


```

среднее
```{r}
mean(r_heights)
sd(r_heights)
quantile(r_heights)
median(r_heights)
summary(r_heights)
```


Функция sample



```{r}
set.seed(123)
sort(sample(1:49,7))
```


```{r}
set.seed(123)
sam1<-sample(c("камень","ножницы","бумага"),30,replace = T)
barplot(table(sam1))
```

```{r}
set.seed(123)
sam1<-sample(c("камень","ножницы","бумага"),300,prob = c(1/2,1/3,1/6),replace = T)
barplot(table(sam1))
```
`

```{r}
hist(r_heights,breaks = seq(from=100,to=220,length.out = 100))
```
```{r hist and density}
hist(r_heights,breaks = seq(from=100,to=220,length.out = 100),freq = F)
curve(expr = dnorm(x,mean = m_height,sd=std_height),from = 100,to=220,add = T,col="red")
```


##  Технология  Knitr



### Опции чанков


```{r setup,echo=F}
knitr::opts_chunk$set(warning = FALSE)
```


```{r load}
library(MASS)
var123=runif(10)
print(var123)
```
